//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalBakeClient.StockServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockServiceClient.IStockService")]
    public interface IStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/ReduceStock", ReplyAction="http://tempuri.org/IStockService/ReduceStockResponse")]
        BakeryStockLibrary.Item ReduceStock(BakeryStockLibrary.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/ReduceStock", ReplyAction="http://tempuri.org/IStockService/ReduceStockResponse")]
        System.Threading.Tasks.Task<BakeryStockLibrary.Item> ReduceStockAsync(BakeryStockLibrary.Item item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockServiceChannel : MetalBakeClient.StockServiceClient.IStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceClient : System.ServiceModel.ClientBase<MetalBakeClient.StockServiceClient.IStockService>, MetalBakeClient.StockServiceClient.IStockService {
        
        public StockServiceClient() {
        }
        
        public StockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BakeryStockLibrary.Item ReduceStock(BakeryStockLibrary.Item item) {
            return base.Channel.ReduceStock(item);
        }
        
        public System.Threading.Tasks.Task<BakeryStockLibrary.Item> ReduceStockAsync(BakeryStockLibrary.Item item) {
            return base.Channel.ReduceStockAsync(item);
        }
    }
}
